### ISSUE TITLE
Transparent base layer issue

### ISSUE THREAD

**Issue by steffest** [pixfabrik/magrathea#1]
Just a very small "imperfection"
If the base layer contains transparent pixels, and you add "overlays"
The transparent parts of the base image are not cleared at redraw, cause weirdness.
<img width="721" alt="image" src="https://github.com/pixfabrik/magrathea/assets/763047/1b428ef2-80a7-4c8e-b1f8-0fe54d44b4e2">

I know: the base layer should not be transparent anyway, but still.
I just wanted to let you know that people do test your app and give feedback :-)

(It would probably also speed up adoption if people could import "normal" indexed color image formats like GIF and PNG8 so they can at least start with common image editors and go from there)

**Comment by iangilman** [comment]
Awesome, thank you for the bug report! And good thought on the import options. 😊

**Comment by iangilman** [comment]
Fixed in Version 6!
